#!/usr/bin/env python3
"""Search small finite semigroups for nonzero H^1 in coordinate Hopf modules.

We use the augmentation character on A = ell_1(S).  For a coordinate ideal
E_T <= M = ell_infty(S), the right action is

    (m . delta_s)(r) = m(s*r).

The derivation identity is D(ab) = a.D(b) + D(a).b.
All ranks are computed exactly over Q with sympy.
"""

from __future__ import annotations

import argparse
import itertools

import sympy as sp


def associative(table: tuple[int, ...], n: int) -> bool:
    def mul(a: int, b: int) -> int:
        return table[a * n + b]

    return all(
        mul(mul(a, b), c) == mul(a, mul(b, c))
        for a in range(n)
        for b in range(n)
        for c in range(n)
    )


def stable_coordinate_ideal(table: tuple[int, ...], n: int, support: tuple[int, ...]) -> bool:
    """E_T is stable under m -> m.delta_s for every s."""
    support_set = set(support)
    return all(
        table[s * n + r] not in support_set
        for s in range(n)
        for r in range(n)
        if r not in support_set
    )


def cohomology_dimension(
    table: tuple[int, ...], n: int, support: tuple[int, ...]
) -> tuple[int, int, int]:
    pos = {r: j for j, r in enumerate(support)}
    width = len(support)

    def var(a: int, r: int) -> int:
        return a * width + pos[r]

    rows: list[list[int]] = []
    # D(delta_a delta_b) = D(delta_b) + D(delta_a).delta_b.
    for a in range(n):
        for b in range(n):
            ab = table[a * n + b]
            for r in support:
                row = [0] * (n * width)
                row[var(ab, r)] += 1
                row[var(b, r)] -= 1
                br = table[b * n + r]
                if br in pos:
                    row[var(a, br)] -= 1
                rows.append(row)

    constraint = sp.Matrix(rows)
    derivation_dim = n * width - constraint.rank()

    # Inner derivation generated by m: delta_a.m - m.delta_a.
    inner = sp.zeros(n * width, width)
    for a in range(n):
        for r in support:
            inner[var(a, r), pos[r]] += 1
            ar = table[a * n + r]
            if ar in pos:
                inner[var(a, r), pos[ar]] -= 1
    inner_dim = inner.rank()
    assert (constraint * inner).is_zero_matrix
    return derivation_dim - inner_dim, derivation_dim, inner_dim


def search(n: int, stop_after_first: bool) -> int:
    tables_checked = 0
    semigroups = 0
    module_cases = 0
    hits = 0
    for table in itertools.product(range(n), repeat=n * n):
        tables_checked += 1
        if not associative(table, n):
            continue
        semigroups += 1
        for mask in range(1, 1 << n):
            support = tuple(r for r in range(n) if mask & (1 << r))
            if not stable_coordinate_ideal(table, n, support):
                continue
            module_cases += 1
            hdim, ddim, idim = cohomology_dimension(table, n, support)
            if hdim:
                hits += 1
                print(
                    "HIT",
                    f"n={n}",
                    f"support={support}",
                    f"H1_dim={hdim}",
                    f"Der_dim={ddim}",
                    f"Inn_dim={idim}",
                )
                print("table")
                for a in range(n):
                    print(" ", table[a * n : (a + 1) * n])
                if stop_after_first:
                    return 1
    print(
        "SUMMARY",
        f"n={n}",
        f"tables={tables_checked}",
        f"semigroups={semigroups}",
        f"module_cases={module_cases}",
        f"hits={hits}",
    )
    return hits


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, required=True)
    parser.add_argument("--all-hits", action="store_true")
    args = parser.parse_args()
    search(args.n, stop_after_first=not args.all_hits)


if __name__ == "__main__":
    main()
