#!/usr/bin/env python3
"""Finite consistency checks for the compact-open rectangle proof.

For small finite abelian groups, enumerate every subgroup H, construct the
characteristic functions of all Weyl translates of the Haar projector on H,
and verify that their complex span is exactly the full function space on
N={(g,chi): chi(g)=1}.
"""

from itertools import combinations, product

import numpy as np


def add(a, b, moduli):
    return tuple((x + y) % n for x, y, n in zip(a, b, moduli))


def neg(a, moduli):
    return tuple((-x) % n for x, n in zip(a, moduli))


def pairing(character, point, moduli):
    angle = sum(k * x / n for k, x, n in zip(character, point, moduli))
    return np.exp(2j * np.pi * angle)


def generated(seed, universe, moduli):
    subgroup = {tuple(0 for _ in moduli)}
    changed = True
    while changed:
        changed = False
        candidates = list(subgroup) + list(seed)
        for a in candidates:
            for b in candidates:
                c = add(a, b, moduli)
                if c not in subgroup:
                    subgroup.add(c)
                    changed = True
                c = add(a, neg(b, moduli), moduli)
                if c not in subgroup:
                    subgroup.add(c)
                    changed = True
    return frozenset(subgroup)


def all_subgroups(universe, moduli):
    subgroups = set()
    # Every subgroup of the small test groups is generated by some subset.
    for size in range(len(universe) + 1):
        for seed in combinations(universe, size):
            subgroups.add(generated(seed, universe, moduli))
    return sorted(subgroups, key=lambda h: (len(h), sorted(h)))


def coset_reps(universe, subgroup, moduli):
    unseen = set(universe)
    reps = []
    while unseen:
        rep = min(unseen)
        coset = {add(rep, h, moduli) for h in subgroup}
        reps.append(rep)
        unseen -= coset
    return reps


def check(moduli):
    universe = list(product(*[range(n) for n in moduli]))
    dual = universe
    subgroups = all_subgroups(universe, moduli)
    commuting = [
        (g, chi)
        for g in universe
        for chi in dual
        if abs(pairing(chi, g, moduli) - 1) < 1e-9
    ]
    row = {pair: i for i, pair in enumerate(commuting)}

    columns = []
    covered = set()
    for subgroup in subgroups:
        annihilator = frozenset(
            chi
            for chi in dual
            if all(abs(pairing(chi, h, moduli) - 1) < 1e-9 for h in subgroup)
        )
        rectangle = {(g, chi) for g in subgroup for chi in annihilator}
        assert rectangle <= set(commuting)
        covered |= rectangle
        for a in coset_reps(universe, subgroup, moduli):
            for alpha in coset_reps(dual, annihilator, moduli):
                vector = np.zeros(len(commuting), dtype=complex)
                for u, eta in rectangle:
                    vector[row[(u, eta)]] = (
                        pairing(eta, a, moduli)
                        * np.conjugate(pairing(alpha, u, moduli))
                    )
                columns.append(vector)

    assert covered == set(commuting)
    matrix = np.column_stack(columns)
    rank = np.linalg.matrix_rank(matrix, tol=1e-8)
    assert rank == len(commuting)
    return len(universe), len(subgroups), len(commuting), len(columns), rank


def main():
    print("finite KD characteristic-span verification")
    for moduli in [(2,), (3,), (4,), (5,), (6,), (2, 2), (2, 3), (2, 2, 2)]:
        order, nsub, ncomm, ncols, rank = check(moduli)
        label = "x".join(f"Z/{n}Z" for n in moduli)
        print(
            f"{label}: PASS; order={order}; subgroups={nsub}; "
            f"|N|={ncomm}; pure_chars={ncols}; rank={rank}"
        )
    print("ALL CHECKS PASSED")


if __name__ == "__main__":
    main()
